build:
  version: "3.0"

accounts:
  message: "Welcome to the SupDev accounts related to local APIs"
  contactDetails:
    name: "Supriya Kumari - Backend Lead"
    email: "sia@sup.dev"
  onCallSupport:
    - 8007546098
    - 8142060028