build:
  version: "3.0"

accounts:
  message: "Welcome to the SupDev accounts related to local APIs"
  contactDetails:
    name: "Supriya Kumari - Backend Lead"
    email: "{cipher}ac6ec9a13d27b0bcb844075233d6ff5810decd03efa1cbcfbd7862eb2f5b350b"
  onCallSupport:
    - 8007546098
    - 8142060028
