build:
  version: "1.0.0"

cards:
  message: "Welcome to the SupDev cards related to local APIs"
  contactDetails:
    name: "Supriya - Backend Lead"
    email: "supriya@sup.dev"
  onCallSupport:
    - (+91) 8007546098
    - (+91) 8142060028