build:
  version: "1.1.0"

loans:
  message: "Welcome to the SupDev loans related to prod(s) APIs"
  contactDetails:
    name: "Jennifer Lauren - Product Owner"
    email: "jenniferL@sup.dev"
  onCallSupport:
    - (245) 67080034
    - (245) 67080035
