build:
  version: "1.3.0"

cards:
  message: "Welcome to the SupDev cards related to QA APIs"
  contactDetails:
    name: "Jack Henry - Quality Assurance Lead"
    email: "jackHenry@sup.dev"
  onCallSupport:
    - (116) 43900034
    - (116) 43900033